{% set version = "0.15" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-thinkr
  version: {{ version|replace("-", "_") }}

source:
  fn: thinkr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/thinkr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/thinkr/thinkr_{{ version }}.tar.gz
  sha256: 8fb9043d827447a49806403327ee47e10cce37e0a0a34ffb467337750ce0ae9e

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-assertthat
    - r-crayon
    - r-devtools
    - r-dplyr
    - r-ggplot2
    - r-lazyeval
    - r-lubridate
    - r-magrittr
    - r-officer
    - r-purrr
    - r-readr
    - r-rvg
    - r-stringi
    - r-stringr
    - r-tidyr
  run:
    - r-base
    - r-assertthat
    - r-crayon
    - r-devtools
    - r-dplyr
    - r-ggplot2
    - r-lazyeval
    - r-lubridate
    - r-magrittr
    - r-officer
    - r-purrr
    - r-readr
    - r-rvg
    - r-stringi
    - r-stringr
    - r-tidyr

test:
  commands:
    - $R -e "library('thinkr')"           # [not win]
    - "\"%R%\" -e \"library('thinkr')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=thinkr
  license: GPL-3.0-only
  summary: Some tools for cleaning up messy 'Excel' files to be suitable for R. People who have been working with 'Excel' for years built more or less complicated sheets with names, characters, formats that are not homogeneous. To be able to use them in R nowadays, we built a set of functions that will avoid the majority
    of importation problems and keep all the data at best.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
