appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: pOi02PEmhk4YTfiXwGgrHdK7rHMNIIOM+/3xRYEVxPW1FYxgXbBn+g/DP3sdZkQmdqX9wKHCER4x4+x3nUcr0gcjBXan2/GOuFHwct1VQWGxdF9Ee8PT3YSm4JYobZ1IdlAafQ4VeFj1JlNzk9feslygKWhLC+knIxQ5oEHpqBar31asEDLg/SA6NEf8YHS17xlUSlGYQZTjwnXZ0PLpRyIGc0G3MFbHZ9oG8mr6bnTWcFNALV4sK7790TedzaQ+BI00d09mxaZkazSYNJh6cESIRza4FVc9errT/p5dD7fT3UAu9FHu4ziQmwuLMSx60oQM6MLq+IHA2AMugJnd2pAdIvO+FTM5QnVIgc4cw4ycv6kM1mzjyyxGu1w9+EoFRfu7GnCy+EXym2zLXUWK4lUQpIaIYwY0tog1Vsme7GM3nGl2IiVOKA4egBCyEQn27As+otl7PHxf545AcpPZffgFNEn2j0+l+3jHkSZDwltv4zPCjvCtfLb6QqLEg+aIQ86/pUcYNrrPgmhkiYya6v/sHNgP/0Cw5ETIkkJ6VRfV8bwZByo5uIlvS3n+lwdvKZ7DwKBcNeeGyyx4EUf/SqPPcD2hd9ZiSXNBdQUHVK9Z+dA+T/q8cV1FndKrsuVr+fxoIBjs4TxfqI9FszKN8gYQB3HFNOGvrEIKBwv+0k0=
conda_forge_output_validation: true
